services:
  - type: web
    name: gastro-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGINS
        value: "*"
      - key: JWT_SECRET
        generateValue: true
